In [2]:
import pandas as pd

print(pd.__name__)

pandas

In [4]:
countries = pd.Series(
    data = ['England', 'France', 'Germany', 'Spain', 'United States'],
    index = ['UK', 'FR', 'DE', 'ES', 'US'],
    name = 'countries'
)

display(countries)

UK          England
FR           France
DE          Germany
ES            Spain
US    United States
Name: countries, dtype: str

In [ ]:
print(countries.loc['US'])
print('You get series for this!')
print(countries.loc[['US','UK']])

United States
US    United States
UK          England
Name: countries, dtype: str

DataFrame -- это таблица с данными
Series -- это строка или столбец

In [ ]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902],
}, index=['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ'])
display(countries_df)

countries_df = pd.DataFrame(
    data = [['Англия', 56.29, 133396],
            ['Канада', 38.05, 9984670],
            ['США', 322.28, 9826630],
            ['Россия', 146.24, 17125191],
            ['Украина', 45.5, 603628],
            ['Беларусь;', 9.5, 207600],
            ['Казахстан', 17.04, 2724902]],
    columns = ['country', 'population', 'area'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
)
display(countries_df)

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US     ;США"'      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY  Беларусь;        9.50    207600
KZ  Казахстан       17.04   2724902

О доступе к строкам и столбцам

In [20]:
print('Площадь России:')
countries_df.loc['RU', 'area'] #countries_df.loc['RU'].area

print('Население и площадь России')
countries_df.loc['RU', ['population', 'area']]

Площадь России:
Население и площадь России

population         146.24
area          17125191.00
Name: RU, dtype: float64

Запишем DataFrame в файл

И прочитаем

In [30]:
countries_df.to_csv('data/countries.csv', index=False, sep = ';')

data = pd.read_csv('data/countries.csv', sep = ';')
display(data)

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2     ;США"'      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5  Беларусь;        9.50    207600
6  Казахстан       17.04   2724902